Repository carbonxx/Code-Library, pull requests merged in 2022-10, with the labels that each got.

#26 Python Programs based on CLI and Tkinter Module
  Python/Basics/AdventureGame.py
  Python/Tkinter/AgeCalucator.py
  Python/Tkinter/RockPaperScissors.py
  Python/Tkinter/TemperatureConverter.py
Labels: hacktoberfest, hacktoberfest-accepted

#27 3 sort 1 linked list
  C/7-VTU_lab/bubbleSort.c
  C/Misc/MergeSort.c
  C/Misc/insertionSort.c
  cpp/linkedList.cpp
  cpp/queues/queue.cpp
  cpp/stacks/stack.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#28 Update README.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#29 added backtracking-sudoku problem
  cpp/backtracking/backtracking.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#30 updates
  cpp/backtracking/backtracking.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#34 Documentation
  Programs/cpp/backtracking.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#35 Organized a file in folder + added some readme files
  Instruction and Program/readme.md
  Programming Language/readme.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#36 added palidrome n short resursion related progrmans
  Programs/cpp/recursion/resursion.cpp
  Programs/cpp/strings/palidrome.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#37 Added Pattern programs in CPP
  Programs/cpp/Patterns/Diamond.cpp
  Programs/cpp/Patterns/HalfDiamond.cpp
  Programs/cpp/Patterns/MirrorRightAngleTriangle.cpp
  Programs/cpp/Patterns/NumberRightAngleTriangle.cpp
  Programs/cpp/Patterns/Rectangle.cpp
  Programs/cpp/Patterns/RightAngleTriangle.cpp
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#39 contributed to recursion folder in c
  Programs/C/5-Concept of Recursion/Permutation.c
  Programs/C/5-Concept of Recursion/Power.c
Labels: hacktoberfest, hacktoberfest-accepted

#38 added polymorphism content
  Object Oriented Programming/readme.md
Labels: hacktoberfest, hacktoberfest-accepted

#41 Hacktoberfest-2022
  Programs/C/1-Basic Programs/simplecalculator.c
Labels: hacktoberfest, hacktoberfest-accepted

#48 Store and display of values
  Programs/C/4-Concept of Arrays/matrixdis.c
Labels: hacktoberfest, hacktoberfest-accepted

#57 Infix to Postfix.c
  Infix_to_Postfix.c
Labels: hacktoberfest, hacktoberfest-accepted

#58 Documentation
  Infix_to_Postfix.c
  Instruction and Program/readme.md
  Object Oriented Programming/readme.md
  Programming Language/readme.md
  Programs/C/1-Basic Programs/primeNum.c
  Programs/C/1-Basic Programs/simplecalculator.c
  Programs/C/4-Concept of Arrays/matrixadd.c
  Programs/C/4-Concept of Arrays/matrixdis.c
  Programs/C/4-Concept of Arrays/matrixmultication.c
  Programs/C/4-Concept of Arrays/matrixsub.c
  Programs/C/5-Concept of Recursion/Permutation.c
  Programs/C/5-Concept of Recursion/Power.c
  Programs/Python/Basics/Factorial.py
  Programs/Python/Basics/MultiplicationTable.py
  Programs/Python/Basics/Palindrome.py
  Programs/Python/Basics/SumOfNatural.py
  Programs/Python/Basics/leapYear.py
  Programs/Web/html projects/about.css
  Programs/Web/html projects/coffee images/3790f471-400f-4ec8-82a5-215e6a3588ef.jpg-output.png
  Programs/Web/html projects/coffee images/4a1e992f59170a3ae5c6c115cb6f3f88.jpg
  Programs/Web/html projects/coffee images/WhatsApp Image 2022-10-09 at 19.13.18.jpg
  Programs/Web/html projects/coffee images/WhatsApp Image 2022-10-09 at 19.27.54.jpg
  Programs/Web/html projects/coffee images/about.html
  Programs/Web/html projects/coffee images/background img.jpg
  Programs/Web/html projects/coffee images/coffee logo.png
  Programs/Web/html projects/coffee images/coffee-cup-cafe-vector-graphics-tea-png-favpng-uTjyKHK3Tp8E6WM475kn4g2PE.jpg
  Programs/Web/html projects/coffee images/contacts.html
  Programs/Web/html projects/coffee images/home.html
  Programs/Web/html projects/coffee images/images.png
  Programs/Web/html projects/coffee images/numbers.html
  Programs/Web/html projects/coffee images/pexels-photo-1695052.jpeg
  Programs/Web/html projects/coffee web/4a1e992f59170a3ae5c6c115cb6f3f88.jpg
  Programs/Web/html projects/coffee web/about.html
  Programs/Web/html projects/coffee web/col.jpg
  Programs/Web/html projects/coffee web/contacts.html
  Programs/Web/html projects/coffee web/french roaast.jpg
  Programs/Web/html projects/coffee web/fresh-roasted-coffee-beans-500x500.webp
  Programs/Web/html projects/coffee web/home.html
  Programs/Web/html projects/coffee web/hpude blend.webp
  Programs/Web/html projects/coffee web/pexels-photo-1695052.jpeg
  Programs/Web/html projects/coffee web/sales.html
  Programs/Web/html projects/contact.css
  Programs/Web/html projects/home.css
  Programs/Web/html projects/sales.css
  Programs/Web/html projects/simpleIntrestCalci/corsera html/index.html
  Programs/Web/html projects/simpleIntrestCalci/corsera html/style.css
  Programs/Web/html projects/simpleIntrestCalci/corsera html/work.js
  Programs/cpp/Patterns/Diamond.cpp
  Programs/cpp/Patterns/HalfDiamond.cpp
  Programs/cpp/Patterns/MirrorRightAngleTriangle.cpp
  Programs/cpp/Patterns/NumberRightAngleTriangle.cpp
  Programs/cpp/Patterns/Rectangle.cpp
  Programs/cpp/Patterns/RightAngleTriangle.cpp
  Programs/cpp/recursion/resursion.cpp
  Programs/cpp/strings/palidrome.cpp
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#59 improper documentation
  Infix_to_Postfix.c
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#69 Apply a license
  LICENSE
Labels: hacktoberfest, hacktoberfest-accepted

#64 Create fibonacci
  Programs/C/1-Basic Programs/fibonacci.c
Labels: hacktoberfest, hacktoberfest-accepted

#67 armstrong
  Programs/Python/Basics/armstrong.py
Labels: hacktoberfest, hacktoberfest-accepted

#66 Create Calendar
  Programs/Python/Basics/Calendar.py
Labels: hacktoberfest, hacktoberfest-accepted

#86 Update readme.md
  Algorithms/Sorting/HeapSort/readme.md
Labels: hacktoberfest, hacktoberfest-accepted

#89 Create Stack_Linked_List.py
  Programs/Python/Basics/Stack_Linked_List.py
Labels: hacktoberfest, hacktoberfest-accepted
